### ISSUE TITLE
Foraging macro not breaking tree

### ISSUE THREAD

**Issue by BioVC** [PizzaboiBestLegit/Pizza-Client#52]
i use the foraging macro it lantws bonemeals then doesnt break, i put delay to max and the only way it breaks logsis if i turn the macro on then  off again

**Comment by PizzaboiBestLegit** [comment]
weird

**Comment by cuteacc** [comment]
For me, this only happens when using Acacia or Dark Oak (2x2) saplings. All others function as intended, including Jungle 2x2. Though sometimes the macro plants the closest dirt block instead of the furthest, which makes it not able to reach the other dirt blocks. I'm not sure how it works, but maybe it's possible to implement crop aura's plant through blocks here? Thank you for your work :)
